import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <nav className='bg-slate-600 text-white p-2 shadow-md'><a href="https://treatment-court.clark.wa.gov/?id=1"><button className="absolute top-0 right-5 outline outline-1 bg-orange-500 hover:bg-orange-700 text-white py-1 my-3 px-1 rounded">Web Report</button></a><ul className='nav'><li><a href="/">Home</a></li><li><a href="/forms">Forms</a></li></ul></nav>
      {children}</body>
    </html>
  )
}
